[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
clearscreen = "3.0.0"
colored = "2.1.0"
csv = "1.3.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"

